[network]
worker_ip_addr = "127.0.0.1"
worker_port = 65432

[misc]
greeting_msg = "Hello brother"

[behavior]
shutdown_persistence = false

[behavior.caching]
policy = "LRU"
max_size = 1

[logging]
log_level = "debug"
log_directory = "worker/logs"
log_filename = "worker_log.log"

[statistics]
enabled = true
